---
- name: Converge
  hosts: all
  become: true

  vars:
    nodejs_version: "12.4.0"
    nodejs_repo_version: "12.x"
    nodejs_deb_url_prefix: 'deb.nodesource.com/node_12.x/pool/main/n/nodejs'
    nodejs_rpm_url_prefix: 'rpm.nodesource.com/pub_12.x/el/7/x86_64'
    nodejs_install_npm_user: root
    npm_config_prefix: /root/.npm-global
    npm_config_unsafe_perm: "true"
    nodejs_npm_global_packages:
      - node-sass
      - name: jslint
        version: 0.12.0
      - name: yo

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.nodejs
